keys:
  - &users:
    - &karun 1D0BCFCA23E3D1D714D4AC301743F5EEBFA41DA9
  - &hosts:
    - &promethea age1dqafwvry0efcwagplqp8ez0ul9tmlduqhpnsx5wgz36z57d635zszg5k8z
    - &pandora age15jgs3y0uqrxu8027jnrvfc6vsryd6uuyfmtudxspjpfl6y2gqgeqqhj623
    - &xylourgos age1d4r0qx4dtlsc64sp98fdcu85s6a3tfmsdf549hn6jteyhy76naasmqat57
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *karun
        age:
          - *promethea
          - *pandora
          - *xylourgos
  - path_regex: secrets/promethea/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *karun
        age:
          - *promethea
  - path_regex: secrets/pandora/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *karun
        age:
          - *pandora
  - path_regex: secrets/xylourgos/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *karun
        age:
          - *xylourgos
