keys:
  - &users:
    - &karun age1cuj2d45ntqfec2r2jwdk24xujcn43pag8xk9egjfn6v3wvqy9a0snzvs6f
  - &hosts:
    - &blackbox age1dqafwvry0efcwagplqp8ez0ul9tmlduqhpnsx5wgz36z57d635zszg5k8z 
    - &pandora age15jgs3y0uqrxu8027jnrvfc6vsryd6uuyfmtudxspjpfl6y2gqgeqqhj623 
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *karun
      - *blackbox
      - *pandora
  - path_regex: secrets/pandora/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *karun
      - *pandora
  
