{
  imports = [
    ./cliphist.nix
    ./fnott
    ./gammastep.nix
    ./gpg-agent.nix
    ./hypridle.nix
    ./hyprpaper.nix
    ./kdeconnect.nix
    ./mpris-proxy.nix
    ./polkit.nix
    ./psd.nix
    ./solaar.nix
    ./swaync
    ./swayosd.nix
    ./syncthing.nix
    ./tailray.nix
    ./udiskie.nix
  ];
}
