name: Build Servers

on:
  push:
    branches:
      - main
    paths:
      - "flake.lock"
  pull_request:
    paths:
      - "flake.lock"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  build-servers:
    name: Build Servers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hostname:
          - pandora

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Purge non-nix stuff
        uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: rampage

      - name: Install Lix
        uses: DeterminateSystems/nix-installer-action@v13
        with:
          source-url: https://install.lix.systems/lix/lix-installer-x86_64-linux
          diagnostic-endpoint: "" # so eelco can have more personalized self-merges? no thank you
          backtrace: true
          extra-conf: |
            experimental-features = nix-command flakes

      - name: Disable packages with prefetch
        run: |
          sed -i "s|true|false|" system/optional/programs/vmware.nix
          sed -i "s|ciscoPacketTracer8|#ciscoPacketTracer8|" home/programs/school/default.nix

      - name: ${{ matrix.hostname }}
        run: |
          nix build .#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel -L

      - name: sbomnix
        run: |
          name="${{ matrix.hostname }}"
          nix run github:tiiuae/sbomnix#sbomnix -- \
            --csv "${name}.sbom.csv" \
            --cdx "${name}.sbom.cdx.json" \
            --spdx "${name}.sbom.spdx.json" \
            ./result

      - name: vulnxscan
        run: |
          name="${{ matrix.hostname }}"
          nix run github:tiiuae/sbomnix#vulnxscan -- \
            --triage \
            --sbom "${name}.sbom.cdx.json"
          if [ -e vulns.triage.csv ]; then
            grep -v -E "not_vulnerable|fix_not_available" vulns.triage.csv > cve.csv
            if [ $(wc -l < cve.csv) -gt 1 ]; then
              nix run github:nixos/nixpkgs#csv2md -- --columns "0-7,9" cve.csv | tee "${name}.vulnxscan.md"
              echo "### Vulnerability Scan Results for ${{ matrix.hostname }}" >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY
              cat "${name}.vulnxscan.md" >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY
            fi
          fi
