name: Check Flake

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.nix"
      - "**.lock"
      - ".github/workflows/check-flake.yml"
  pull_request:

jobs:
  check-flake:
    name: Check Flake
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Purge non-nix stuff
        uses: wimpysworld/nothing-but-nix@v6
        with:
          hatchet-protocol: cleave

      - name: Install Lix
        uses: DeterminateSystems/nix-installer-action@v18
        with:
          source-url: https://install.lix.systems/lix/lix-installer-x86_64-linux
          diagnostic-endpoint: "" # so eelco can have more personalized self-merges? no thank you
          backtrace: true
          extra-conf: |
            experimental-features = nix-command flakes

      - name: Setup Nix magic cache
        uses: DeterminateSystems/magic-nix-cache-action@v12
        with:
          diagnostic-endpoint: ""

      - name: Check Flake
        run: nix flake check
